worker_processes auto;
error_log /var/log/ngnix/error.log;

events{
    worker_connections 8000;
    muilti_accept on;
}

http{
    include /etc/ngnix/mine.types;
    default_type application/octet-stream;

    server{
        listen 3000;
        root /var/www;
        index index.html index.html;

        location/{
            include /etc/nginx/mine.types;
            try_files $url $url/ /index.html
        }
    }
}